version: '3'
services:
  api:
    build: .
    ports:
      - "8080:8080"
  mongo:
    image: "mongo:4.0.18-xenial"
    ports:
      - "27017:27017"
  rabbitmq:
    image: "rabbitmq:3.8.3-alpine"
    ports:
      - "5672:5672"