version: '3'
services:
  mongo:
    image: "mongo:4.0.18-xenial"
    container_name: mongo-container
    networks:
      default:
        aliases:
          - mongo-host
    ports:
      - "27017:27017"
  api:
    build: .
    container_name: meeting-agendas-api
    ports:
      - "8080:8080"