version: '3'
services:
  mongo:
    image: "mongo:4.0.18-xenial"
    container_name: mongo-container
    networks:
      default:
        aliases:
          - mongo-host
    ports:
      - "27017:27017"
  rabbitmq:
    image: "rabbitmq:3.7-alpine"
    container_name: rabbit-mq
    ports:
      - "5672:5672"
    networks:
      default:
        aliases:
          - rabbitmq-host
  api:
    build: .
    container_name: meeting-agendas-api
    ports:
      - "8080:8080"