spring:
  data:
    mongodb:
      database: meeting-agendas
      host: mongo-host:27017

app:
  scheduler:
    close-voting-session:
      execution-interval-ms: 30000 # Every 30s
  rest-client:
    user-info:
      host: https://user-info.herokuapp.com